name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - run: pip install pytest
    # - name: Run pytest
    #   run: |
    #     pytest \
    #     --maxfail=1 \
    #     --disable-warnings \
    #     --ignore=src/chapter2/hello/test \
    #     --ignore=src/chapter2/my_happy/test 